"""add token and cost columns to api_usage

Revision ID: a3c8d3b2c9c7
Revises: d611032c322b
Create Date: 2026-03-31 22:19:31.332420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c8d3b2c9c7'
down_revision: Union[str, Sequence[str], None] = 'd611032c322b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage', sa.Column('input_tokens', sa.Integer(), nullable=False))
    op.add_column('api_usage', sa.Column('output_tokens', sa.Integer(), nullable=False))
    op.add_column('api_usage', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False))
    op.drop_column('api_usage', 'tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('api_usage', 'cost_usd')
    op.drop_column('api_usage', 'output_tokens')
    op.drop_column('api_usage', 'input_tokens')
    # ### end Alembic commands ###
