version: '3.8'

services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "3000:3000"
    platform: linux/amd64
    depends_on:
      - mongo
    environment:
      DB_URL: mongodb://root:pass@mongo:27017/project1db?authSource=admin
